# site properties and page defaults
title: Transport Systems & Logistics Laboratory
share_title: Transport Systems and Logistics Laboratory (TSL), Imperial College London
subtitle: Imperial College London
description: "The Transport Systems & Logistics Laboratory at Imperial College London undertakes research transport operations, with focus on computational optimisation, autonomy and logistics."
keywords: [tsl, transport systems, transport, logistics, autonomous vehicles, maritime transport, optimization, imperial, imperial college london]
author: "Transport Systems & Logistics Laboratory"
footer: images/background_imp-light.jpg
proofer: false
header-dark: false


url:  https://transport-systems.imperial.ac.uk
baseurl: ''
# Sitemap settings
sitemap:
  filename: sitemap.xml
  exclude:
    - "/404.html"
    - "/.bundle/"
    - "/_cite/"

# site social media and other links
links:
  email: p.angeloudis@imperial.ac.uk
  # orcid: 0000-0001-8713-9213
  google-scholar: pyOTFWoAAAAJ
  github: tsl-imperial
  # twitter: YourLabHandle
  # youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-minifier



# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts
  - _redirects

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff

jekyll-minifier:
  exclude: ['*.xml', '*.json', '*.txt']  # Files to exclude from minification
  remove_spaces_inside_tags: true        # Default: true
  remove_multi_spaces: true              # Default: true
  remove_comments: true                  # Default: true
  preserve_php: true                     # Default: false
  remove_intertag_spaces: true           # Default: false
  remove_quotes: false                   # Default: false
  compress_css: false                    # Default: true
  compress_javascript: false             # Default: true
  compress_json: false                   # Default: true
  simple_doctype: false                  # Default: false
  remove_script_attributes: false        # Default: false
  remove_style_attributes: false         # Default: false
  remove_link_attributes: false          # Default: false
  remove_form_attributes: false          # Default: false
  remove_input_attributes: false         # Default: false
  remove_javascript_protocol: false      # Default: false
  remove_http_protocol: false            # Default: false
  remove_https_protocol: false           # Default: false
  preserve_line_breaks: false            # Default: false
  simple_boolean_attributes: false       # Default: false
  compress_js_templates: false           # Default: false
